language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
  - phpenv config-rm xdebug.ini

install:
  - travis_wait composer update --prefer-stable
  - phpenv config-add /tmp/xdebug.ini

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
